# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microsite', '0002_auto_20190313_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='content',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='content',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='microsite.Section'),
        ),
        migrations.AddField(
            model_name='section',
            name='name',
            field=models.CharField(default='my-content', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20, verbose_name='Content type'),
            preserve_default=False,
        ),
    ]
